[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://arcaos.webflow.io"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, Content-Type, Accept"